### ISSUE TITLE
Incorrect Response

### ISSUE THREAD

**Issue by tfalamu** [Mastersam07/ncovid-19-api#6] opened 2020-05-08 10:47 UTC
API results don't seem to match those on the NCDC website

**Comment by Mastersam07** [comment] 2020-05-08 11:07
Seems the data has been rearranged on NCDC website causing the scrapers not to auto-update successfully.

**Comment by Mastersam07** [comment] 2020-05-08 11:07
The issue is now being treated.

**Comment by tfalamu** [comment] 2020-05-08 11:21
Terrific. How soon will there be a fix?

**Comment by Mastersam07** [comment] 2020-05-08 11:56
Less than an hour. I am making some commits already.

**Comment by Mastersam07** [comment] 2020-05-08 13:00
Issue fixed in the latest commit. The API structure is also maintained.

**Comment by tfalamu** [comment] 2020-05-08 13:37
Awesome, thanks. One more question, how often is the data refreshed?

**Comment by Mastersam07** [comment] 2020-05-08 14:24
NCDC gives their update somewhere around 10 pm. The scrapers are set to refresh the data by 11:30 pm in case NCDC gives their update late.

**Comment by tfalamu** [comment] 2020-05-08 14:29
Terrific, glad an api like this is available. Saves me a whole bunch of time.

**Comment by Mastersam07** [comment] 2020-05-08 14:32
😁😁😁.......... You could send a PR and add your app/solution to the showcase area of the readme if you see it fit.

**Comment by Mastersam07** [comment] 2020-05-08 14:39
Will close this issue if there's nothing else.🙂

**Comment by tfalamu** [comment] 2020-05-08 14:40
Definitely, I'll be honored!

**Comment by tfalamu** [comment] 2020-05-08 14:41
I think I have all I need for now, you can close the issue.

**Comment by Mastersam07** [comment] 2020-05-08 14:45
This issue has been fixed and is now closed

**Closed as completed by Mastersam07** 2020-05-08 14:45 UTC
Labels: bug
